language: ruby
rvm:
- 2.2.0
bundler_args: "--without production"
addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: X5A5M6n6y4ugH37Ggkepbl5S3UTYYU+sNr5MNrL1s2iKjAdlfh2sFeymqlaW9qnNS5uYuAExqhXcBa8L7pwxpcz5UWjyfU+8y6j+WGNrT/7mxMFQdVtEQP6+YqeKFv2Q1aL012TX387H6DHMUgYgDreT7B8JAijLLDp5VcNq7+4=
before_script:
- bundle exec rake db:create db:schema:load
deploy:
  provider: ninefold
  app_id: '13503'
  auth_token:
    secure: FQY2xJby88HaoAnR3uicAbBvtkEhqYifuVV/enAs1Qo3y3uCH0oUB+ZjBAo0qCLJoCW5QjIUL6H0yWM8BGgvpJSe+yeW+4MsDRxPG0nKieAt95as70AysYJCD8tBkUerWJ7C2YqHkDhT7VcV8mq5d6w/Hgrw3PHCen3XFrJSh9I=
  on:
    repo: ambethia/ambethia
