language: ruby
rvm:
- 2.2.2
bundler_args: "--without production"
addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: X5A5M6n6y4ugH37Ggkepbl5S3UTYYU+sNr5MNrL1s2iKjAdlfh2sFeymqlaW9qnNS5uYuAExqhXcBa8L7pwxpcz5UWjyfU+8y6j+WGNrT/7mxMFQdVtEQP6+YqeKFv2Q1aL012TX387H6DHMUgYgDreT7B8JAijLLDp5VcNq7+4=
before_script:
- bundle exec rake db:create db:schema:load
