development: &common
  adapter: postgresql
  database: ambethia
  host: localhost
  encoding: unicode
  min_messages: WARNING

production:
  <<: *common

test:
  <<: *common
  database: ambethia_test
